/* The football career map. Worlds unlock as XP/lessons accumulate. */

export const WORLDS = [
  {
    id: 'training-ground',
    name: 'Training Ground',
    nameUz: 'Mashq maydoni',
    emoji: '🥅', colour: '#35c46a', dot: '🟢',
    tier: 1,
    unlockXp: 0,
    blurb: 'Harflar, raqamlar, chizish, sanash',
  },
  {
    id: 'academy',
    name: 'Football Academy',
    nameUz: 'Futbol akademiyasi',
    emoji: '🏟️', colour: '#3a86ff', dot: '🔵',
    tier: 2,
    unlockXp: 300,
    blurb: 'Alifbo tugadi + sonlar 0–20',
  },
  {
    id: 'junior-league',
    name: 'Junior League',
    nameUz: 'Kichik liga',
    emoji: '🏆', colour: '#f6c945', dot: '🟡',
    tier: 3,
    unlockXp: 900,
    blurb: "So'zlar + qo'shish va ayirish",
  },
  {
    id: 'pro-league',
    name: 'Pro League',
    nameUz: 'Pro liga',
    emoji: '⭐', colour: '#ff8c42', dot: '🟠',
    tier: 4,
    unlockXp: 1800,
    blurb: "O'qish + ko'paytirish va bo'lish",
  },
  {
    id: 'champions',
    name: 'Champions League',
    nameUz: 'Chempionlar ligasi',
    emoji: '🔥', colour: '#e5383b', dot: '🔴',
    tier: 5,
    unlockXp: 3200,
    blurb: 'Murakkab ingliz tili va matematika',
  },
  {
    id: 'world-cup',
    name: 'World Cup of Knowledge',
    nameUz: 'Bilimlar Jahon Kubogi',
    emoji: '🌍', colour: '#8338ec', dot: '🏆',
    tier: 6,
    unlockXp: 5000,
    blurb: 'Faqat ingliz tilida — yakuniy sinov',
  },
];

/* Difficulty tiers described for the UI (section 15). */
export const TIERS = [
  { tier: 1, name: 'TRAINING',     uz: 'MASHQ',        skills: ['Harflar', 'Raqamlar', 'Chizish', 'Sanash'] },
  { tier: 2, name: 'ACADEMY',      uz: 'AKADEMIYA',    skills: ["Oddiy so'zlar", "Qo'shish", 'Ayirish'] },
  { tier: 3, name: 'JUNIOR',       uz: 'KICHIK LIGA',  skills: ['Qisqa gaplar', 'Ikki xonali hisob', "Ko'paytirish"] },
  { tier: 4, name: 'PROFESSIONAL', uz: 'PROFESSIONAL', skills: ["O'qish matnlari", "Ko'paytirish/bo'lish", 'Masalalar'] },
  { tier: 5, name: 'CHAMPION',     uz: 'CHEMPION',     skills: ['Faqat inglizcha', "Ko'p bosqichli hisob", "Uzun matnlar"] },
];

/* Lesson catalogue. Each entry is a *generator descriptor* — the lesson engine
   turns it into concrete steps, so we never hand-author hundreds of lessons. */
export const LESSONS = [
  /* ---------------- ENGLISH ---------------- */
  { id: 'en-letters-1', subject: 'english', world: 'training-ground', tier: 1,
    title: 'Letters A – F', titleUz: 'Harflar A – F', emoji: '🔤',
    kind: 'letters', params: { from: 'A', to: 'F' } },
  { id: 'en-letters-2', subject: 'english', world: 'training-ground', tier: 1,
    title: 'Letters G – M', titleUz: 'Harflar G – M', emoji: '🔤',
    kind: 'letters', params: { from: 'G', to: 'M' } },
  { id: 'en-letters-3', subject: 'english', world: 'academy', tier: 2,
    title: 'Letters N – S', titleUz: 'Harflar N – S', emoji: '🔤',
    kind: 'letters', params: { from: 'N', to: 'S' } },
  { id: 'en-letters-4', subject: 'english', world: 'academy', tier: 2,
    title: 'Letters T – Z', titleUz: 'Harflar T – Z', emoji: '🔤',
    kind: 'letters', params: { from: 'T', to: 'Z' } },
  { id: 'en-phonics-1', subject: 'english', world: 'academy', tier: 2,
    title: 'Sounds: -at, -an', titleUz: 'Tovushlar: -at, -an', emoji: '🔊',
    kind: 'phonics', params: { patterns: ['-at', '-an'] } },
  { id: 'en-phonics-2', subject: 'english', world: 'junior-league', tier: 3,
    title: 'Sounds: -all, -ick', titleUz: 'Tovushlar: -all, -ick', emoji: '🔊',
    kind: 'phonics', params: { patterns: ['-all', '-ick', '-oal'] } },
  { id: 'en-vocab-1', subject: 'english', world: 'academy', tier: 2,
    title: 'First Words', titleUz: "Birinchi so'zlar", emoji: '⚽',
    kind: 'vocab', params: { tier: 't1' } },
  { id: 'en-vocab-2', subject: 'english', world: 'junior-league', tier: 3,
    title: 'Football Words', titleUz: "Futbol so'zlari", emoji: '🥅',
    kind: 'vocab', params: { tier: 't2' } },
  { id: 'en-vocab-3', subject: 'english', world: 'pro-league', tier: 4,
    title: 'Match Day Words', titleUz: "O'yin kuni so'zlari", emoji: '📣',
    kind: 'vocab', params: { tier: 't3' } },
  { id: 'en-sent-1', subject: 'english', world: 'junior-league', tier: 3,
    title: 'First Sentences', titleUz: 'Birinchi gaplar', emoji: '📝',
    kind: 'sentences', params: { band: 'easy' } },
  { id: 'en-sent-2', subject: 'english', world: 'pro-league', tier: 4,
    title: 'Action Sentences', titleUz: 'Harakat gaplari', emoji: '🏃',
    kind: 'sentences', params: { band: 'medium' } },
  { id: 'en-sent-3', subject: 'english', world: 'champions', tier: 5,
    title: 'Long Sentences', titleUz: 'Uzun gaplar', emoji: '📖',
    kind: 'sentences', params: { band: 'hard' } },
  { id: 'en-story-1', subject: 'english', world: 'junior-league', tier: 3,
    title: 'Story: The Ball', titleUz: "Hikoya: To'p", emoji: '📚',
    kind: 'story', params: { storyId: 'story-1' } },
  { id: 'en-story-2', subject: 'english', world: 'pro-league', tier: 4,
    title: 'Story: New Boots', titleUz: 'Hikoya: Yangi butsalar', emoji: '📚',
    kind: 'story', params: { storyId: 'story-2' } },
  { id: 'en-story-3', subject: 'english', world: 'champions', tier: 5,
    title: 'Story: The Big Match', titleUz: "Hikoya: Katta o'yin", emoji: '📚',
    kind: 'story', params: { storyId: 'story-3' } },
  { id: 'en-story-4', subject: 'english', world: 'world-cup', tier: 6,
    title: 'Story: Training Every Day', titleUz: 'Hikoya: Har kuni mashq', emoji: '📚',
    kind: 'story', params: { storyId: 'story-4' } },

  /* ---------------- MATH ---------------- */
  { id: 'ma-count-1', subject: 'math', world: 'training-ground', tier: 1,
    title: 'Count 1 – 5', titleUz: 'Sanash 1 – 5', emoji: '🔢',
    kind: 'counting', params: { diff: 1 } },
  { id: 'ma-count-2', subject: 'math', world: 'training-ground', tier: 1,
    title: 'Count 1 – 10', titleUz: 'Sanash 1 – 10', emoji: '🔢',
    kind: 'counting', params: { diff: 2 } },
  { id: 'ma-count-3', subject: 'math', world: 'academy', tier: 2,
    title: 'Count 1 – 20', titleUz: 'Sanash 1 – 20', emoji: '🔢',
    kind: 'counting', params: { diff: 3 } },
  { id: 'ma-compare-1', subject: 'math', world: 'academy', tier: 2,
    title: 'More or Less?', titleUz: "Ko'p yoki kam?", emoji: '⚖️',
    kind: 'compare', params: { diff: 1 } },
  { id: 'ma-add-1', subject: 'math', world: 'academy', tier: 2,
    title: 'Scoring Goals (+)', titleUz: "Gol urish (qo'shish)", emoji: '➕',
    kind: 'add', params: { diff: 1 } },
  { id: 'ma-add-2', subject: 'math', world: 'junior-league', tier: 3,
    title: 'Add to 20', titleUz: "20 gacha qo'shish", emoji: '➕',
    kind: 'add', params: { diff: 2 } },
  { id: 'ma-add-3', subject: 'math', world: 'junior-league', tier: 3,
    title: 'Column Addition', titleUz: "Ustunda qo'shish", emoji: '🧮',
    kind: 'column-add', params: { diff: 4 } },
  { id: 'ma-sub-1', subject: 'math', world: 'academy', tier: 2,
    title: 'Take Away (−)', titleUz: 'Ayirish', emoji: '➖',
    kind: 'sub', params: { diff: 1 } },
  { id: 'ma-sub-2', subject: 'math', world: 'junior-league', tier: 3,
    title: 'Subtract to 20', titleUz: '20 gacha ayirish', emoji: '➖',
    kind: 'sub', params: { diff: 2 } },
  { id: 'ma-sub-3', subject: 'math', world: 'pro-league', tier: 4,
    title: 'Column Subtraction', titleUz: 'Ustunda ayirish', emoji: '🧮',
    kind: 'column-sub', params: { diff: 4 } },
  { id: 'ma-mul-1', subject: 'math', world: 'pro-league', tier: 4,
    title: 'Teams and Balls (×)', titleUz: "Jamoalar va to'plar", emoji: '✖️',
    kind: 'mul', params: { diff: 1 } },
  { id: 'ma-mul-2', subject: 'math', world: 'pro-league', tier: 4,
    title: 'Times Tables 2–5', titleUz: "Ko'paytirish 2–5", emoji: '✖️',
    kind: 'mul', params: { diff: 2 } },
  { id: 'ma-div-1', subject: 'math', world: 'pro-league', tier: 4,
    title: 'Share the Balls (÷)', titleUz: "To'plarni bo'lish", emoji: '➗',
    kind: 'div', params: { diff: 1 } },
  { id: 'ma-div-2', subject: 'math', world: 'champions', tier: 5,
    title: 'Division Practice', titleUz: "Bo'lish mashqi", emoji: '➗',
    kind: 'div', params: { diff: 3 } },
  { id: 'ma-en-1', subject: 'math', world: 'junior-league', tier: 3,
    title: 'Math in English 1', titleUz: 'Inglizcha matematika 1', emoji: '🗣️',
    kind: 'math-english', params: { tier: 1 } },
  { id: 'ma-en-2', subject: 'math', world: 'pro-league', tier: 4,
    title: 'Math in English 2', titleUz: 'Inglizcha matematika 2', emoji: '🗣️',
    kind: 'math-english', params: { tier: 3 } },
  { id: 'ma-word-1', subject: 'math', world: 'pro-league', tier: 4,
    title: 'Word Problems', titleUz: 'Masalalar', emoji: '🧠',
    kind: 'word-problems', params: { level: 3 } },
  { id: 'ma-word-2', subject: 'math', world: 'world-cup', tier: 6,
    title: 'English Word Problems', titleUz: 'Inglizcha masalalar', emoji: '🌍',
    kind: 'word-problems', params: { level: 5, englishOnly: true } },

  /* ---------------- WRITING ---------------- */
  { id: 'wr-lines-1', subject: 'writing', world: 'training-ground', tier: 1,
    title: 'Dribble Practice', titleUz: 'Dribling mashqi', emoji: '〰️',
    kind: 'strokes', params: { set: 'lines' } },
  { id: 'wr-curves-1', subject: 'writing', world: 'training-ground', tier: 1,
    title: 'Curve Practice', titleUz: 'Egri chiziqlar', emoji: '🌀',
    kind: 'strokes', params: { set: 'curves' } },
  { id: 'wr-upper-1', subject: 'writing', world: 'training-ground', tier: 1,
    title: 'Write A – F', titleUz: 'A – F yozamiz', emoji: '✏️',
    kind: 'trace-letters', params: { from: 'A', to: 'F', case: 'upper' } },
  { id: 'wr-upper-2', subject: 'writing', world: 'academy', tier: 2,
    title: 'Write G – M', titleUz: 'G – M yozamiz', emoji: '✏️',
    kind: 'trace-letters', params: { from: 'G', to: 'M', case: 'upper' } },
  { id: 'wr-upper-3', subject: 'writing', world: 'academy', tier: 2,
    title: 'Write N – Z', titleUz: 'N – Z yozamiz', emoji: '✏️',
    kind: 'trace-letters', params: { from: 'N', to: 'Z', case: 'upper' } },
  { id: 'wr-lower-1', subject: 'writing', world: 'junior-league', tier: 3,
    title: 'Small letters a – m', titleUz: 'Kichik harflar a – m', emoji: '🔡',
    kind: 'trace-letters', params: { from: 'A', to: 'M', case: 'lower' } },
  { id: 'wr-num-1', subject: 'writing', world: 'training-ground', tier: 1,
    title: 'Write 0 – 9', titleUz: '0 – 9 yozamiz', emoji: '🔟',
    kind: 'trace-numbers', params: { from: 0, to: 9 } },
  { id: 'wr-words-1', subject: 'writing', world: 'junior-league', tier: 3,
    title: 'Write Football Words', titleUz: "Futbol so'zlarini yozamiz", emoji: '⚽',
    kind: 'trace-words', params: { words: ['BALL', 'GOAL', 'TEAM', 'RUN'] } },
  { id: 'wr-sent-1', subject: 'writing', world: 'pro-league', tier: 4,
    title: 'Write a Sentence', titleUz: 'Gap yozamiz', emoji: '📝',
    kind: 'trace-words', params: { words: ['I HAVE A BALL', 'ALI CAN RUN'] } },
];

export function lessonsFor(subject) {
  return LESSONS.filter(l => l.subject === subject);
}
export function lessonById(id) {
  return LESSONS.find(l => l.id === id);
}
export function worldById(id) {
  return WORLDS.find(w => w.id === id);
}

/* ---------------- TROPHY CABINET ---------------- */
export const TROPHIES = [
  { id: 'first-touch', name: 'First Touch', nameUz: 'Birinchi teginish', emoji: '👟', desc: 'Birinchi darsni tugat', test: s => s.stats.lessonsCompleted >= 1 },
  { id: 'hat-trick',   name: 'Hat-trick',   nameUz: 'Xet-trik',        emoji: '🎩', desc: "Ketma-ket 3 ta to'g'ri javob", test: s => s.stats.bestStreakAnswers >= 3 },
  { id: 'goal-machine',name: 'Goal Machine',nameUz: 'Gol mashinasi',   emoji: '⚽', desc: '50 ta gol ur', test: s => s.stats.goals >= 50 },
  { id: 'century',     name: 'Century',     nameUz: 'Yuzlik',          emoji: '💯', desc: '100 ta gol ur', test: s => s.stats.goals >= 100 },
  { id: 'bookworm',    name: 'Reader',      nameUz: "O'quvchi",        emoji: '📚', desc: 'Bitta hikoyani tugat', test: s => s.stats.storiesRead >= 1 },
  { id: 'penman',      name: 'Neat Writer', nameUz: 'Chiroyli yozuvchi', emoji: '✏️', desc: '20 ta harf yoz', test: s => s.stats.tracedItems >= 20 },
  { id: 'calculator',  name: 'Calculator',  nameUz: 'Hisoblovchi',     emoji: '🧮', desc: "100 ta misol yech", test: s => s.stats.mathAnswers >= 100 },
  { id: 'streak-3',    name: '3 Day Streak',nameUz: '3 kunlik seriya', emoji: '🔥', desc: '3 kun ketma-ket mashq qil', test: s => s.streak.best >= 3 },
  { id: 'streak-7',    name: '7 Day Streak',nameUz: '7 kunlik seriya', emoji: '🔥', desc: '7 kun ketma-ket mashq qil', test: s => s.streak.best >= 7 },
  { id: 'academy-cap', name: 'Academy Cap', nameUz: 'Akademiya nishoni', emoji: '🏟️', desc: 'Akademiyani och', test: s => s.xp >= 300 },
  { id: 'junior-cup',  name: 'Junior Cup',  nameUz: 'Kichik kubok',    emoji: '🏆', desc: 'Kichik ligani och', test: s => s.xp >= 900 },
  { id: 'pro-badge',   name: 'Pro Badge',   nameUz: 'Pro nishon',      emoji: '⭐', desc: 'Pro ligani och', test: s => s.xp >= 1800 },
  { id: 'champion',    name: 'Champion',    nameUz: 'Chempion',        emoji: '🥇', desc: 'Chempionlar ligasini och', test: s => s.xp >= 3200 },
  { id: 'world-cup',   name: 'World Cup',   nameUz: 'Jahon Kubogi',    emoji: '🌍', desc: 'Jahon kubogini och', test: s => s.xp >= 5000 },
  { id: 'game-on',     name: 'Game On',     nameUz: "O'yinchi",        emoji: '🎮', desc: "5 ta mini o'yin o'yna", test: s => s.stats.gamesPlayed >= 5 },
  { id: 'sharp-shooter', name: 'Sharp Shooter', nameUz: 'Aniq zarba', emoji: '🎯', desc: "Bitta o'yinda 100% aniqlik", test: s => s.stats.perfectGames >= 1 },
];
